### ISSUE TITLE
Samsung t705

### ISSUE THREAD

**Issue by ruckenwind** [YasefDogan/youtube-vanced-for-android-5.1.1-update-youtube-error-FIX-for-VANCED-#2]
Still got issue with Samsung t705 (galaxy tab s). Android version 5.0.2. Same error - need newer version while trying access video.

**Comment by YasefDogan** [comment]
yes it happend again i will share a hotfix whit only adblock modules today then i eill work on orher patches

**Comment by YasefDogan** [comment]
> Still got issue with Samsung t705 (galaxy tab s). Android version 5.0.2. Same error - need newer version while trying access video.

realesed an hotfix

**Comment by YasefDogan** [comment]
> Still got issue with Samsung t705 (galaxy tab s). Android version 5.0.2. Same error - need newer version while trying access video. addeda new realese
