### ISSUE TITLE
Laggy 60 fps videos

### ISSUE THREAD

**Issue by FatihOzer-AVFA** [YasefDogan/youtube-vanced-for-android-5.1.1-update-youtube-error-FIX-for-VANCED-#4]
I am using your edited youtube on android 5.1.1. Videos play at any resolution without any problem. But 60 fps 1080p and 60 fps 720p videos are laggy and have shutter. Sound is playing normaly but video come later. 60 fps videos  play like 10 fps. If i change quality 480p, video continue to play normal. Thanks for your help

**Comment by FatihOzer-AVFA** [comment]
I noticed that My AndroidBox has problem. Full screen 60 gps videos are laggy only.

**Comment by YasefDogan** [comment]
> I noticed that My AndroidBox has problem. Full screen 60 gps videos are laggy only.

i reccomend using https://github.com/yuliskov/SmartTube this project for android tv boxes
