### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by testermania** [YasefDogan/youtube-vanced-for-android-5.1.1-update-youtube-error-FIX-for-VANCED-#6]
Today I had a problem connecting to the library. Is it the same for you? After clear data had connection error.

**Comment by gboy97** [comment]
Hello! I have the same problem, probably something broke with microsg. You can still use the app in the meantime if you exit your Google account. Hoping for @YasefDogan to solve the issue yet again!

**Comment by YasefDogan** [comment]
>  Today I had a problem connecting to the library. Is it the same for you? After clear data had connection error.

İs it error 400

**Comment by gboy97** [comment]
Yes it's a 400 error also for me. Do you already know what the problem could be?

**Comment by testermania** [comment]
> > Today I had a problem connecting to the library. Is it the same for you? After clear data had connection error.
> 
> İs it error 400

yes, It looks like a microg problem.

**Comment by YasefDogan** [comment]
> Yes it's a 400 error also for me. Do you already know what the problem could be?

Working on it fix will be came in a few days

**Comment by YasefDogan** [comment]
> > Yes it's a 400 error also for me. Do you already know what the problem could be?
> 
> Working on it fix will be came in a few days

İts not like we expected the fix is not coming soon

**Comment by YasefDogan** [comment]
>  Today I had a problem connecting to the library. Is it the same for you? After clear data had connection error.

Actually tehere is a fix but also there isnt, İt wont be fully functional, Go to settings(your prophile photo then) >  revanced settings > other options (the last option) > spoof app version and spoof the app version to 17.35.35 or 17.33.42 Shorts will work, For the normal videos You have to add them on a playlist( for example watch later press on the 3 down right left to text > click add to watch later > there will be a pop up saying go to list click on it> then you can play videos from the playlist)  you have to play videos from the playlist, Otherwise it wont open the videos, videos in the main screen are not clickable.  For now its the best i can do

**Comment by Snoctis** [comment]
Can I download videos and watch them?

**Comment by YasefDogan** [comment]
> Can I download videos and watch them?
> 

You can but you have to add them on a playlist for now

**Comment by Nehalemna** [comment]
I can't watch videos now it says update the app

**Comment by gboy97** [comment]
Hi! I don't really know how things work. I saw that the official app fixed the issue, can you just eee what they did and copy It? Sorry if this Is a dumb question

**Comment by Sufyanijaz** [comment]
> I can't watch videos now it says update the app
1st do the upper mentioned step (spoofing app version) then go to settings / revanced  settings / misellaneous settings / then there off spoof player parameter 

Now you can play any video on yt but there is a catch by doing such setting , when you play a video it will start to play normally but it we throw a error in the middle of the video , saying encounter a playback error something , I hope somebody fix that issue

Sorry for my bad English  , I hope it helps yeah

**Comment by Nehalemna** [comment]
> > I can't watch videos now it says update the app
> > 1st do the upper mentioned step (spoofing app version) then go to settings / revanced  settings / misellaneous settings / then there off spoof player parameter
> 
> Now you can play any video on yt but there is a catch by doing such setting , when you play a video it will start to play normally but it we throw a error in the middle of the video , saying encounter a playback error something , I hope somebody fix that issue
> 
> Sorry for my bad English , I hope it helps yeah

It happens after every 1min

**Comment by Nehalemna** [comment]
> Hi! I don't really know how things work. I saw that the official app fixed the issue, can you just eee what they did and copy It? Sorry if this Is a dumb question

Yes the official app has to do patch things and I don't know how to even do those things

**Comment by Sufyanijaz** [comment]
> > > I can't watch videos now it says update the app
> > > 1st do the upper mentioned step (spoofing app version) then go to settings / revanced  settings / misellaneous settings / then there off spoof player parameter
> > 
> > 
> > Now you can play any video on yt but there is a catch by doing such setting , when you play a video it will start to play normally but it we throw a error in the middle of the video , saying encounter a playback error something , I hope somebody fix that issue
> > Sorry for my bad English , I hope it helps yeah
> 
> It happens after every 1min

Yup sadly it sucks , for me it happen after ever 5 minutes

**Comment by Nehalemna** [comment]
> > > > I can't watch videos now it says update the app
> > > > 1st do the upper mentioned step (spoofing app version) then go to settings / revanced  settings / misellaneous settings / then there off spoof player parameter
> > > 
> > > 
> > > Now you can play any video on yt but there is a catch by doing such setting , when you play a video it will start to play normally but it we throw a error in the middle of the video , saying encounter a playback error something , I hope somebody fix that issue
> > > Sorry for my bad English , I hope it helps yeah
> > 
> > 
> > It happens after every 1min
> 
> Yup sadly it sucks , for me it happen after ever 5 minutes

What should we do man?u got any idea?

**Comment by Sufyanijaz** [comment]
> > > > > I can't watch videos now it says update the app
> > > > > 1st do the upper mentioned step (spoofing app version) then go to settings / revanced  settings / misellaneous settings / then there off spoof player parameter
> > > > 
> > > > 
> > > > Now you can play any video on yt but there is a catch by doing such setting , when you play a video it will start to play normally but it we throw a error in the middle of the video , saying encounter a playback error something , I hope somebody fix that issue
> > > > Sorry for my bad English , I hope it helps yeah
> > > 
> > > 
> > > It happens after every 1min
> > 
> > 
> > Yup sadly it sucks , for me it happen after ever 5 minutes
> 
> What should we do man?u got any idea?

Wait for the professional do fix it or install custom rom (comes with its on consequences )

**Comment by Nehalemna** [comment]
> > > > > > I can't watch videos now it says update the app
> > > > > > 1st do the upper mentioned step (spoofing app version) then go to settings / revanced  settings / misellaneous settings / then there off spoof player parameter
> > > > > 
> > > > > 
> > > > > Now you can play any video on yt but there is a catch by doing such setting , when you play a video it will start to play normally but it we throw a error in the middle of the video , saying encounter a playback error something , I hope somebody fix that issue
> > > > > Sorry for my bad English , I hope it helps yeah
> > > > 
> > > > 
> > > > It happens after every 1min
> > > 
> > > 
> > > Yup sadly it sucks , for me it happen after ever 5 minutes
> > 
> > 
> > What should we do man?u got any idea?
> 
> Wait for the professional do fix it or install custom rom (comes with its on consequences )

Hopefully it comes ay dude u on ig?

**Comment by Sufyanijaz** [comment]
> > > > > > > I can't watch videos now it says update the app
> > > > > > > 1st do the upper mentioned step (spoofing app version) then go to settings / revanced  settings / misellaneous settings / then there off spoof player parameter
> > > > > > 
> > > > > > 
> > > > > > Now you can play any video on yt but there is a catch by doing such setting , when you play a video it will start to play normally but it we throw a error in the middle of the video , saying encounter a playback error something , I hope somebody fix that issue
> > > > > > Sorry for my bad English , I hope it helps yeah
> > > > > 
> > > > > 
> > > > > It happens after every 1min
> > > > 
> > > > 
> > > > Yup sadly it sucks , for me it happen after ever 5 minutes
> > > 
> > > 
> > > What should we do man?u got any idea?
> > 
> > 
> > Wait for the professional do fix it or install custom rom (comes with its on consequences )
> 
> Hopefully it comes ay dude u on ig?
Yes my Id  (oyee__sufi)it will have a cat dp

**Comment by Nehalemna** [comment]
> > > > > > > > I can't watch videos now it says update the app
> > > > > > > > 1st do the upper mentioned step (spoofing app version) then go to settings / revanced  settings / misellaneous settings / then there off spoof player parameter
> > > > > > > 
> > > > > > > 
> > > > > > > Now you can play any video on yt but there is a catch by doing such setting , when you play a video it will start to play normally but it we throw a error in the middle of the video , saying encounter a playback error something , I hope somebody fix that issue
> > > > > > > Sorry for my bad English , I hope it helps yeah
> > > > > > 
> > > > > > 
> > > > > > It happens after every 1min
> > > > > 
> > > > > 
> > > > > Yup sadly it sucks , for me it happen after ever 5 minutes
> > > > 
> > > > 
> > > > What should we do man?u got any idea?
> > > 
> > > 
> > > Wait for the professional do fix it or install custom rom (comes with its on consequences )
> > 
> > 
> > Hopefully it comes ay dude u on ig?
> > Yes my Id  (oyee__sufi)it will have a cat dp

Ok gave u req it's neh11_ u will see me standing

**Comment by YasefDogan** [comment]
> Hi! I don't really know how things work. I saw that the official app fixed the issue, can you just eee what they did and copy It? Sorry if this Is a dumb question

Now i saw that and copiying the thing but its actually the same thing, it just deafaults it, but i will fix playback issue to on the next realase but you have to watch the videos from playlist thats my main problem about that

**Comment by YasefDogan** [comment]
check out the new realeses you have to add videos to playlist then you can play the videos

**Comment by YasefDogan** [comment]
dont forget to install gms core!! because of the playback isssue microg has changed

**Comment by YasefDogan** [comment]
> > > > > > > > > I can't watch videos now it says update the app
> > > > > > > > > 1st do the upper mentioned step (spoofing app version) then go to settings / revanced  settings / misellaneous settings / then there off spoof player parameter
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Now you can play any video on yt but there is a catch by doing such setting , when you play a video it will start to play normally but it we throw a error in the middle of the video , saying encounter a playback error something , I hope somebody fix that issue
> > > > > > > > Sorry for my bad English , I hope it helps yeah
> > > > > > > 
> > > > > > > 
> > > > > > > It happens after every 1min
> > > > > > 
> > > > > > 
> > > > > > Yup sadly it sucks , for me it happen after ever 5 minutes
> > > > > 
> > > > > 
> > > > > What should we do man?u got any idea?
> > > > 
> > > > 
> > > > Wait for the professional do fix it or install custom rom (comes with its on consequences )
> > > 
> > > 
> > > Hopefully it comes ay dude u on ig?
> > > Yes my Id  (oyee__sufi)it will have a cat dp
> 
> Ok gave u req it's neh11_ u will see me standing



> > > > > > > > I can't watch videos now it says update the app
> > > > > > > > 1st do the upper mentioned step (spoofing app version) then go to settings / revanced  settings / misellaneous settings / then there off spoof player parameter
> > > > > > > 
> > > > > > > 
> > > > > > > Now you can play any video on yt but there is a catch by doing such setting , when you play a video it will start to play normally but it we throw a error in the middle of the video , saying encounter a playback error something , I hope somebody fix that issue
> > > > > > > Sorry for my bad English , I hope it helps yeah
> > > > > > 
> > > > > > 
> > > > > > It happens after every 1min
> > > > > 
> > > > > 
> > > > > Yup sadly it sucks , for me it happen after ever 5 minutes
> > > > 
> > > > 
> > > > What should we do man?u got any idea?
> > > 
> > > 
> > > Wait for the professional do fix it or install custom rom (comes with its on consequences )
> > 
> > 
> > Hopefully it comes ay dude u on ig?
> > Yes my Id  (oyee__sufi)it will have a cat dp



> Hi! I don't really know how things work. I saw that the official app fixed the issue, can you just eee what they did and copy It? Sorry if this Is a dumb question

try the new realese it daulted almost everything and fixec the playback issue that you guys are facing but still have to add them on a playlist
