### ISSUE TITLE
Shorts option not showing

### ISSUE THREAD

**Issue by Nehalemna** [YasefDogan/youtube-vanced-for-android-5.1.1-update-youtube-error-FIX-for-VANCED-#7]
Hello yasef!thanks for making this version for us ppl...but this version doesn't have a "shorts" button so I can't see shorts

**Comment by YasefDogan** [comment]
> Hello yasef!thanks for making this version for us ppl...but this version doesn't have a "shorts" button so I can't see shorts 


Click your profile picture (top right)/ open settings/ open revanced settings / open interface settings(cant remember cant bebthe actualcname can be ui settings ect.)/ click on shorts component you can enable and disable it from there
